# Generated by Django 3.1.3 on 2021-10-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('seg_id', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('transcript', models.TextField()),
                ('clip_score', models.FloatField()),
                ('clip_matched_visual_seg_ids', models.TextField()),
                ('clip_explanations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisualSeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('seg_id', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('clip_score', models.FloatField()),
                ('clip_matched_audio_seg_ids', models.TextField()),
                ('clip_explanations', models.TextField()),
            ],
        ),
    ]
