# Generated by Django 3.1.3 on 2021-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('seg_id', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('length', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionVisual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('seg_id', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('length', models.FloatField()),
                ('type', models.CharField(choices=[('IN', 'Inline'), ('EX', 'Extended')], default='IN', max_length=2)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('problem_description', models.CharField(max_length=1000)),
                ('visual_seg_id', models.IntegerField()),
                ('audio_seg_id', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('length', models.FloatField()),
                ('describe_visual', models.BooleanField()),
                ('describe_audio', models.BooleanField()),
                ('is_ignored', models.BooleanField()),
                ('is_fixed', models.BooleanField()),
            ],
        ),
    ]
